name: build
on:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.11'
          - '3.10'
          - '3.9'
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          path: ${{ github.workspace }}/test
          main: test.py
          run: true
          python_version: ${{ matrix.python }}
      - name: Ensure file exists
        shell: bash
        run: |
          cd "${{ github.workspace }}/test"
          if ! [ -f dist/test.bin ]; then
            tree
            echo "Error: dist/test.bin is missing!"
            exit 1
          fi
      - name: Upload test.bin as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-${{ matrix.python }}
          path: ${{ github.workspace }}/test/dist/test.bin
  test-no-run:
    name: Test Without Running
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          path: ${{ github.workspace }}/test
          main: test_error.py
          run: false
      - name: Ensure file exists
        shell: bash
        run: |
          cd "${{ github.workspace }}/test"
          if ! [ -f dist/test_error.bin ]; then
            tree
            echo "Error: dist/test_error.bin is missing!"
            exit 1
          fi
